"""Tests for LLM router and mock provider."""

import pytest
import asyncio

from app.integrations.mock_provider import MockProvider


@pytest.mark.asyncio
async def test_mock_provider_generate():
    provider = MockProvider()
    result = await provider.generate("system", "Tell me about pricing", max_tokens=100)
    assert "Executive Summary" in result


@pytest.mark.asyncio
async def test_mock_provider_generic():
    provider = MockProvider()
    result = await provider.generate("system", "Generate a section", max_tokens=100)
    assert "generated by the AI assistant" in result


@pytest.mark.asyncio
async def test_mock_provider_test_connection():
    provider = MockProvider()
    result = await provider.test_connection()
    assert result["ok"] is True
    assert result["model"] == "mock"


def test_mask_key():
    from app.services.settings_service import mask_key
    assert mask_key("sk-ant-1234567890abcdef") == "**************cdef"
    assert mask_key("abc") == "****"
    assert mask_key("") == "****"
    assert mask_key("abcd") == "****"
    assert mask_key("abcde") == "*bcde"
