"""Mock AI provider for testing without API keys."""

from typing import Any

from app.integrations.base_provider import BaseAIProvider


class MockProvider(BaseAIProvider):
    provider_name = "mock"

    async def generate(self, system_prompt: str, user_prompt: str, max_tokens: int = 4096) -> str:
        if "narrative" in user_prompt.lower() or "pricing" in user_prompt.lower():
            return (
                "## Executive Summary\n\n"
                "We are pleased to present this commercial offer tailored to your organization's needs. "
                "Our solution delivers enterprise-grade capabilities with a clear return on investment.\n\n"
                "## Proposed Solution\n\n"
                "Based on our analysis of your requirements, we recommend a comprehensive package "
                "that includes platform licensing, implementation services, and ongoing support.\n\n"
                "## Investment Overview\n\n"
                "The pricing outlined in the accompanying table reflects our commitment to providing "
                "competitive value. All line items have been structured to align with your stated budget "
                "parameters and procurement timeline.\n\n"
                "## Next Steps\n\n"
                "1. Review and confirm the scope of services\n"
                "2. Schedule a technical deep-dive session\n"
                "3. Finalize contract terms\n"
                "4. Target go-live within 8 weeks of signing\n\n"
                "We look forward to partnering with you on this initiative."
            )
        return (
            "This section has been generated by the AI assistant based on the provided context. "
            "It contains professionally written content suitable for business documents. "
            "In production mode, this would be generated by Claude with full context awareness."
        )

    async def test_connection(self) -> dict[str, Any]:
        return {"ok": True, "message": "Mock provider always available", "model": "mock"}
